### ISSUE TITLE
[BUG] Issue with setContext when updating @openfeature/core from 0.0.25 to 0.0.26

### ISSUE THREAD

**Issue by nguyennick197** [open-feature/js-sdk#834]
EDIT: just did some testing and this was working on version 0.0.25, but still breaks on 0.0.26

### Observed behavior

`setContext` is throwing an error after updating from 0.0.23 to 0.026. 

This is the error thrown: 
```
TypeError
Cannot read properties of undefined (reading 'entries')
```

Error happens when running this code:
```typescript
export const setOpenFeatureTargetingKey = async (uuid: string) =>
  await OpenFeature.setContext({
    targetingKey: uuid,
  })
```  

Error is pointing to this section of the code:
```typescript
const oldContext = this._context;
this._context = context;
const defaultContextNameProviders = Array.from(this._clientProviders.entries()).filter(([name]) => !this._namedProviderContext.has(name)).reduce((acc, [name, provider]) => {
   acc.push({ name, provider });
   return acc;
}, []);
```

### Expected Behavior

No error is thrown when downgrading back to 0.0.23 and context is set.

### Steps to reproduce

```typescript
import { LaunchDarklyClientProvider } from '@openfeature/launchdarkly-client-provider'
import { OpenFeature, InMemoryProvider } from '@openfeature/react-sdk'

export const initOpenFeature = () => {
  const ldClientSideId = process.env.VITE_LAUNCH_DARKLY_CLIENT_SIDE_ID

  if (ldClientSideId) {
    const ldOptions = {
      streaming: true,
    }
    const ldOpenFeatureProvider = new LaunchDarklyClientProvider(
      ldClientSideId,
      ldOptions
    )
    // @ts-expect-error Silences "'LaunchDarklyClientProvider' is not assignable to parameter of type 'Provider'"
    OpenFeature.setProvider('openFeatureClient', ldOpenFeatureProvider)
  } else {
    OpenFeature.setProvider(new InMemoryProvider())
  }
}

export const setOpenFeatureTargetingKey = async (uuid: string) =>
  await OpenFeature.setContext({
    targetingKey: uuid,
  })

export const clearOpenFeatureTargetingKey = async () =>
  await OpenFeature.clearContext()
```

**Comment by nguyennick197** [comment]
Thanks for the response @toddbaert! I really appreciate your help with this.

I'm using npm and didn't receive warnings warnings about mismatched versions during the install. 

This is my package.json:
```javascript
{
  "name": “app-name”,
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    ...
    "@openfeature/core": "^0.0.26",
    "@openfeature/launchdarkly-client-provider": "^0.2.1",
    "@openfeature/react-sdk": "^0.1.0-experimental",
    "@openfeature/web-sdk": "^0.4.12",
    ...
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
   "engines": {
    "node": ">=18.12.1 <19",
    "npm": "9.x"
  },
  "resolutions": {
    "styled-components": "^5"
  },
  "lint-staged": {
    "**/*.{js[x],ts[x],md,json,html,scss}": "prettier --write"
  }
}
```

I tried removing the `@openfeature/core` and `@openfeature/web-sdk` packages, but that gives me a build error for the `@openfeature/launchdarkly-client-provider`:

```
Error: Build failed with 2 errors:
node_modules/@openfeature/launchdarkly-client-provider/index.esm.js:1:124: ERROR: Could not resolve "@openfeature/web-sdk"
node_modules/@openfeature/react-sdk/dist/esm/index.js:2:47: ERROR: Could not resolve "@openfeature/web-sdk"
    at failureErrorWithLog (/Users/nick/Documents/GitHub/heard-app/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/nick/Documents/GitHub/heard-app/node_modules/esbuild/lib/main.js:1058:25
    at /Users/nick/Documents/GitHub/heard-app/node_modules/esbuild/lib/main.js:1525:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 124,
        file: 'node_modules/@openfeature/launchdarkly-client-provider/index.esm.js',
        length: 22,
        line: 1,
        lineText: "import { ErrorCode, OpenFeatureEventEmitter, ProviderStatus, GeneralError, ProviderEvents, StandardResolutionReasons } from '@openfeature/web-sdk';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@openfeature/web-sdk" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@openfeature/web-sdk"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 47,
        file: 'node_modules/@openfeature/react-sdk/dist/esm/index.js',
        length: 22,
        line: 2,
        lineText: 'import { ProviderEvents, ProviderStatus } from "@openfeature/web-sdk";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@openfeature/web-sdk" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@openfeature/web-sdk"'
    }
  ],
  warnings: []
}
```

**Comment by beeme1mr** [comment]
Hey @nguyennick197, could you please remove just `@openfeature/core` from your package.json and try again? I could recommend deleting your `node_modules` before running `npm install`.

**Comment by toddbaert** [comment]
Ya, something is fishy here. Take a look at the React demo app's [package.json](https://github.com/open-feature/react-test-app/blob/c3c65ad80e266b59890d8212ade0d1626ba444d4/package.json#L6). Note that the _only_ SDK we declare there is the react SDK.

If you check the [package.lock.json](https://github.com/open-feature/react-test-app/blob/c3c65ad80e266b59890d8212ade0d1626ba444d4/package-lock.json#L3093-L3116), however, you will see both `core` and the `web-sdk` are defined there (NPM resolved them transitively). This is what we'd expect to see.

**Comment by toddbaert** [comment]
@nguyennick197 any news on this one?

**Comment by toddbaert** [comment]
Oh actually that's a good call-out though! `legacy-peer-deps` will certainly cause similar issues for others (TBH that setting scares be, but I know it was needed for legacy reasons). Hopefully others with similar issues will stumble onto your issue!
